In [1]:
import pandas as pd

In [2]:
origin_data = pd.read_csv('./last_data.txt', sep=",")
origin_data

,Unnamed: 0,id,address,gu,dong,mac_score,lot_score,burgerking_score,seveneleven_score,cu_score,...,total_count,first,second,third,first_mapx,first_mapy,second_mapx,second_mapy,third_mapx,third_mapy
0,0,0,서울특별시,NaN,NaN,0.00,0.00,0.0,0.00,0.00,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1,서울특별시 종로구,NaN,NaN,0.00,0.00,0.0,0.00,0.00,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,2,서울특별시 종로구 청운동,종로구,청운동,0.00,0.00,0.0,0.00,0.00,...,1,상봉동,동선동1가,문배동,37.596267,127.085704,37.592065,127.018260,37.536423,126.969346
3,3,3,서울특별시 종로구 신교동,종로구,신교동,0.00,0.00,0.0,0.00,0.13,...,1,중림동,이태원동,영등포동8가,37.558715,126.965840,37.536700,126.992151,37.527015,126.905253
4,4,4,서울특별시 종로구 궁정동,종로구,궁정동,0.00,0.00,0.0,0.00,0.00,...,0,삼청동,인의동,효제동,37.585404,126.982123,37.573102,126.997921,37.572859,127.003417
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
488,488,488,서울특별시 강동구 둔촌동,강동구,둔촌동,3.33,0.00,0.0,0.85,0.67,...,17,광장동,신도림동,쌍문동,37.546992,127.103926,37.509454,126.880425,37.652731,127.028710
489,489,489,서울특별시 강동구 암사동,강동구,암사동,0.00,1.25,0.0,1.06,1.73,...,34,홍은동,신대방동,오류동,37.591560,126.938775,37.492678,126.917721,37.494129,126.840746
490,490,490,서울특별시 강동구 성내동,강동구,성내동,3.33,1.25,10.0,2.55,2.67,...,67,합정동,남현동,한남동,37.549046,126.911558,37.474116,126.976721,37.533889,127.003955
491,491,491,서울특별시 강동구 천호동,강동구,천호동,3.33,1.25,0.0,4.68,2.93,...,74,남학동,하왕십리동,보문동3가,37.560410,126.990860,37.562462,127.029586,37.584277,127.017551
492,492,492,서울특별시 강동구 강일동,강동구,강일동,0.00,1.25,0.0,0.64,0.53,...,13,신사동,돈암동,북아현동,37.595711,126.909195,37.598415,127.020288,37.561666,126.956170

In [3]:
elementary_school_data = pd.read_csv('./학교/초등학교.txt')
elementary_school_data['gu'] = elementary_school_data.apply(lambda x:x["address"].split()[1], axis=1)
elementary_school_data['dong'] = elementary_school_data.apply(lambda x:x["address"].split()[2], axis=1)

middle_school_data = pd.read_csv('./학교/중학교.txt')
middle_school_data['gu'] = middle_school_data.apply(lambda x:x["address"].split()[1], axis=1)
middle_school_data['dong'] = middle_school_data.apply(lambda x:x["address"].split()[2], axis=1)

high_school_data = pd.read_csv('./학교/고등학교.txt')
high_school_data['gu'] = high_school_data.apply(lambda x:x["address"].split()[1], axis=1)
high_school_data['dong'] = high_school_data.apply(lambda x:x["address"].split()[2], axis=1)

In [4]:
new_elementary = elementary_school_data.groupby("dong")
new_elementary = pd.DataFrame(new_elementary["address"].count())
new_elementary.columns = ["elementary_count"]

new_middle = middle_school_data.groupby("dong")
new_middle = pd.DataFrame(new_middle["address"].count())
new_middle.columns = ["middle_count"]

new_high = high_school_data.groupby("dong")
new_high = pd.DataFrame(new_high["address"].count())
new_high.columns = ["high_count"]

In [5]:
origin_data = pd.merge(origin_data,new_elementary,on="dong" ,how="left").fillna(0)
origin_data["elementary_count"] = origin_data["elementary_count"].apply(lambda x:int(x))

origin_data = pd.merge(origin_data,new_middle,on="dong" ,how="left").fillna(0)
origin_data["middle_count"] = origin_data["middle_count"].apply(lambda x:int(x))

origin_data = pd.merge(origin_data,new_high,on="dong" ,how="left").fillna(0)
origin_data["high_count"] = origin_data["high_count"].apply(lambda x:int(x))
origin_data

,Unnamed: 0,id,address,gu,dong,mac_score,lot_score,burgerking_score,seveneleven_score,cu_score,...,third,first_mapx,first_mapy,second_mapx,second_mapy,third_mapx,third_mapy,elementary_count,middle_count,high_count
0,0,0,서울특별시,0,0,0.00,0.00,0.0,0.00,0.00,...,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0
1,1,1,서울특별시 종로구,0,0,0.00,0.00,0.0,0.00,0.00,...,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0
2,2,2,서울특별시 종로구 청운동,종로구,청운동,0.00,0.00,0.0,0.00,0.00,...,문배동,37.596267,127.085704,37.592065,127.018260,37.536423,126.969346,1,1,3
3,3,3,서울특별시 종로구 신교동,종로구,신교동,0.00,0.00,0.0,0.00,0.13,...,영등포동8가,37.558715,126.965840,37.536700,126.992151,37.527015,126.905253,0,0,0
4,4,4,서울특별시 종로구 궁정동,종로구,궁정동,0.00,0.00,0.0,0.00,0.00,...,효제동,37.585404,126.982123,37.573102,126.997921,37.572859,127.003417,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
488,488,488,서울특별시 강동구 둔촌동,강동구,둔촌동,3.33,0.00,0.0,0.85,0.67,...,쌍문동,37.546992,127.103926,37.509454,126.880425,37.652731,127.028710,4,3,2
489,489,489,서울특별시 강동구 암사동,강동구,암사동,0.00,1.25,0.0,1.06,1.73,...,오류동,37.591560,126.938775,37.492678,126.917721,37.494129,126.840746,3,2,1
490,490,490,서울특별시 강동구 성내동,강동구,성내동,3.33,1.25,10.0,2.55,2.67,...,한남동,37.549046,126.911558,37.474116,126.976721,37.533889,127.003955,2,1,0
491,491,491,서울특별시 강동구 천호동,강동구,천호동,3.33,1.25,0.0,4.68,2.93,...,보문동3가,37.560410,126.990860,37.562462,127.029586,37.584277,127.017551,3,2,1
492,492,492,서울특별시 강동구 강일동,강동구,강일동,0.00,1.25,0.0,0.64,0.53,...,북아현동,37.595711,126.909195,37.598415,127.020288,37.561666,126.956170,3,2,1

In [6]:
park_data = pd.read_csv('./공원/공원.txt')
park_data['gu'] = park_data.apply(lambda x:x["address"].split()[1], axis=1)
park_data['dong'] = park_data.apply(lambda x:x["address"].split()[2], axis=1)
park_data

,Unnamed: 0,title,address,roadAddress,mapx,mapy,category,description,telephone,link,gu,dong
0,0,청운<b>공원</b>,서울특별시 종로구 청운동 3-55,NaN,308920,554836,"여행,명소>도시,테마공원",NaN,NaN,NaN,종로구,청운동
1,1,무궁화동산,서울특별시 종로구 궁정동 55-3,NaN,309416,554054,"여행,명소>근린공원",NaN,02-2148-4147,NaN,종로구,궁정동
2,2,<b>공원</b>,서울특별시 종로구 효자동,NaN,309494,553947,"여행,명소>근린공원",NaN,NaN,NaN,종로구,효자동
3,3,인왕산<b>공원</b>,서울특별시 종로구 옥인동,NaN,308352,553903,"여행,명소>근린공원",NaN,NaN,NaN,종로구,옥인동
4,4,해맞이동산,서울특별시 종로구 옥인동,NaN,308765,553928,"여행,명소>근린공원",NaN,NaN,NaN,종로구,옥인동
...,...,...,...,...,...,...,...,...,...,...,...,...
1774,1774,천일골목<b>공원</b>,서울특별시 강동구 천호동,NaN,324044,549613,"여행,명소>근린공원",NaN,NaN,NaN,강동구,천호동
1775,1775,벌말근린<b>공원</b>,서울특별시 강동구 강일동,NaN,327469,551160,"여행,명소>근린공원",NaN,NaN,NaN,강동구,강일동
1776,1776,능골근린<b>공원</b>,서울특별시 강동구 강일동,NaN,327240,550805,"여행,명소>근린공원",NaN,NaN,NaN,강동구,강일동
1777,1777,근린<b>공원</b>,서울특별시 강동구 강일동 343-3,NaN,327542,552344,"여행,명소>근린공원",NaN,NaN,NaN,강동구,강일동
1778,1778,강일<b>공원</b>,서울특별시 강동구 강일동,NaN,327256,552241,"여행,명소>근린공원",NaN,NaN,NaN,강동구,강일동

In [7]:
new_park = park_data.groupby("dong")
new_park = pd.DataFrame(new_park["address"].count())
new_park.columns = ["park_count"]

In [8]:
origin_data = pd.merge(origin_data,new_park,on="dong" ,how="left").fillna(0)
origin_data["park_count"] = origin_data["park_count"].apply(lambda x:int(x))
origin_data

,Unnamed: 0,id,address,gu,dong,mac_score,lot_score,burgerking_score,seveneleven_score,cu_score,...,first_mapx,first_mapy,second_mapx,second_mapy,third_mapx,third_mapy,elementary_count,middle_count,high_count,park_count
0,0,0,서울특별시,0,0,0.00,0.00,0.0,0.00,0.00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0,0
1,1,1,서울특별시 종로구,0,0,0.00,0.00,0.0,0.00,0.00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0,0
2,2,2,서울특별시 종로구 청운동,종로구,청운동,0.00,0.00,0.0,0.00,0.00,...,37.596267,127.085704,37.592065,127.018260,37.536423,126.969346,1,1,3,1
3,3,3,서울특별시 종로구 신교동,종로구,신교동,0.00,0.00,0.0,0.00,0.13,...,37.558715,126.965840,37.536700,126.992151,37.527015,126.905253,0,0,0,0
4,4,4,서울특별시 종로구 궁정동,종로구,궁정동,0.00,0.00,0.0,0.00,0.00,...,37.585404,126.982123,37.573102,126.997921,37.572859,127.003417,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
488,488,488,서울특별시 강동구 둔촌동,강동구,둔촌동,3.33,0.00,0.0,0.85,0.67,...,37.546992,127.103926,37.509454,126.880425,37.652731,127.028710,4,3,2,5
489,489,489,서울특별시 강동구 암사동,강동구,암사동,0.00,1.25,0.0,1.06,1.73,...,37.591560,126.938775,37.492678,126.917721,37.494129,126.840746,3,2,1,13
490,490,490,서울특별시 강동구 성내동,강동구,성내동,3.33,1.25,10.0,2.55,2.67,...,37.549046,126.911558,37.474116,126.976721,37.533889,127.003955,2,1,0,9
491,491,491,서울특별시 강동구 천호동,강동구,천호동,3.33,1.25,0.0,4.68,2.93,...,37.560410,126.990860,37.562462,127.029586,37.584277,127.017551,3,2,1,17
492,492,492,서울특별시 강동구 강일동,강동구,강일동,0.00,1.25,0.0,0.64,0.53,...,37.595711,126.909195,37.598415,127.020288,37.561666,126.956170,3,2,1,4

In [9]:
station_data = pd.read_csv('./역/지하철.txt')
station_data['gu'] = station_data.apply(lambda x:x["address"].split()[1], axis=1)
station_data['dong'] = station_data.apply(lambda x:x["address"].split()[2], axis=1)
station_data

,Unnamed: 0,title,address,roadAddress,mapx,mapy,category,description,telephone,link,gu,dong
0,0,종각역 1호선,서울특별시 종로구 종로1가 54,서울특별시 종로구 종로 55 종로 55,310365,552483,"교통,운수>지하철,전철",NaN,NaN,NaN,종로구,종로1가
1,1,혜화역 4호선,서울특별시 종로구 명륜4가 96-5,서울특별시 종로구 대학로 120 4호선 혜화역,312043,553794,"교통,운수>지하철,전철",NaN,NaN,NaN,종로구,명륜4가
2,2,동대문역 1호선,서울특별시 종로구 창신동 492-1,서울특별시 종로구 종로 302,312842,552633,"교통,운수>지하철,전철",NaN,NaN,NaN,종로구,창신동
3,3,종로3가역 1호선,서울특별시 종로구 종로3가 10-5,서울특별시 종로구 종로 129 종로 129,311171,552503,"교통,운수>지하철,전철",NaN,NaN,NaN,종로구,종로3가
4,4,종로3가역 5호선,서울특별시 종로구 돈의동 39-1,서울특별시 종로구 돈화문로11길 26,311007,552743,"교통,운수>지하철,전철",NaN,02-6311-5341,http://www.smrt.co.kr/Train/Station/Station_in...,종로구,돈의동
...,...,...,...,...,...,...,...,...,...,...,...,...
386,386,고덕역 5호선,서울특별시 강동구 고덕동 310,서울특별시 강동구 고덕로 253 고덕역,325461,550655,"교통,운수>지하철,전철",NaN,02-6311-5521,NaN,강동구,고덕동
387,387,천호역 8호선,서울특별시 강동구 천호동 455,서울특별시 강동구 천호대로 997,322715,548788,"교통,운수>지하철,전철",NaN,02-6311-5471,NaN,강동구,천호동
388,388,길동역 5호선,서울특별시 강동구 길동 378,서울특별시 강동구 양재대로 1480 길동역,324196,548749,"교통,운수>지하철,전철",NaN,02-6311-5491,NaN,강동구,길동
389,389,둔촌오륜역 9호선,서울특별시 강동구 둔촌동 227-7,서울특별시 강동구 강동대로 327,324067,546695,"교통,운수>지하철,전철",NaN,02-2656-0937,NaN,강동구,둔촌동
390,390,강동구청역 8호선,서울특별시 강동구 성내동 319,서울특별시 강동구 올림픽로 550 강동구청역,322468,547959,"교통,운수>지하철,전철",NaN,02-6311-8121,NaN,강동구,성내동

In [10]:
korea_data = pd.read_csv('../data_gdr/1-2. 서울 법정동 주소목록(최종).txt', sep="\t")
korea_data["gu"] = korea_data.apply(lambda x:x["법정동명"].split()[1] if len(x["법정동명"].split())==3 else "",axis=1)
korea_data["dong"] = korea_data.apply(lambda x:x["법정동명"].split()[2] if len(x["법정동명"].split())==3 else "",axis=1)
korea_data.rename(columns={"법정동명":"address"}, inplace = True)
korea_data

           address   gu dong
0            서울특별시
1        서울특별시 종로구
2    서울특별시 종로구 청운동  종로구  청운동
3    서울특별시 종로구 신교동  종로구  신교동
4    서울특별시 종로구 궁정동  종로구  궁정동
..             ...  ...  ...
488  서울특별시 강동구 둔촌동  강동구  둔촌동
489  서울특별시 강동구 암사동  강동구  암사동
490  서울특별시 강동구 성내동  강동구  성내동
491  서울특별시 강동구 천호동  강동구  천호동
492  서울특별시 강동구 강일동  강동구  강일동

[493 rows x 3 columns]

In [58]:
arr = []
for i in korea_data['dong']:
    input_arr = []
    for j in range(len(station_data)):
        if station_data['dong'][j] == i:
            input_arr.append(station_data['title'][j])
    if len(input_arr)>0:
        arr.append(input_arr)
    else:
        arr.append([])

In [59]:
arr

[[],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['경복궁역 3호선'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['광화문역 5호선'],
 [],
 [],
 [],
 [],
 [],
 [],
 ['종각역 1호선'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['안국역 3호선'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['종로3가역 3호선'],
 [],
 ['종로3가역 5호선'],
 [],
 [],
 ['종로3가역 1호선'],
 [],
 [],
 [],
 [],
 [],
 [],
 ['종로5가역 1호선'],
 ['동대문역 4호선'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['혜화역 4호선'],
 [],
 ['동대문역 1호선', '동묘앞역 6호선', '창신역 6호선'],
 ['동묘앞역 1호선'],
 [],
 ['서대문역 5호선'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['을지로입구역 2호선'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['회현역 4호선'],
 [],
 [],
 [],
 [],
 [],
 ['서울역 1호선'],
 [],
 ['서울역 경의중앙선'],
 [],
 [],
 [],
 [],
 ['명동역 4호선'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['충무로역 3호선', '충무로역 4호선'],
 [],
 [],
 [],
 [],
 [],
 ['동대입구역 3호선'],
 ['동대문역사문화공원역 5호선'],
 ['동대문역사문화공원역 4호선'],
 [],
 [],
 ['동대문역사문화공원역 2호선'],
 ['을지로4가역 2호선', '을지로4가역 5호선'],
 [],
 [],
 [],
 [],
 ['을지로3가역 2호선', '을지로3가역 3호선'],
 [],
 [],
 [],
 [],
 [],
 [],
 ['약수역 3호선', '신당역 2호선', '약수역 6호선', '청구역 5호선', '버티고개역 6호선', '청구역 6호선'],
 ['신당역 6호선'],
 [],
 [],
 ['시청역 2호선'],
 ['시청역 1호선'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['녹사평(용산구청)역 6호선'],
 ['숙대입구역 4호선', '남영역 1호선'],
 [],
 [],
 ['서울역 공항철도', '서울역 4호선'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['효창공원앞역 6호선'],
 [],
 ['효창공원앞역 경의중앙선'],
 [],
 [],
 ['삼각지역 4호선', '삼각지역 6호선'],
 ['신용산역 4호선'],
 [],
 ['이촌역 4호선'],
 ['용산역 1호선', '용산역 경의중앙선'],
 ['이촌역 경의중앙선'],
 ['이태원역 6호선'],
 ['한강진역 6호선', '한남역 경의중앙선'],
 [],
 ['서빙고역 경의중앙선'],
 [],
 [],
 [],
 [],
 [],
 ['상왕십리역 2호선'],
 [],
 [],
 ['마장역 5호선'],
 [],
 ['왕십리역 2호선', '왕십리역 경의중앙선', '왕십리역 분당선', '왕십리역 5호선', '한양대역 2호선', '행당역 5호선'],
 ['응봉역 경의중앙선'],
 [],
 ['신금호역 5호선'],
 [],
 ['금호역 3호선'],
 ['옥수역 3호선', '옥수역 경의중앙선'],
 ['뚝섬역 2호선', '서울숲역 분당선'],
 ['성수역 2호선'],
 [],
 ['답십리역 5호선', '신답역 2호선', '용답역 2호선'],
 [],
 ['중곡역 7호선'],
 ['군자역 5호선', '아차산역 5호선', '군자역 7호선'],
 ['강변역 2호선', '구의역 2호선'],
 ['광나루역 5호선'],
 ['뚝섬유원지역 7호선'],
 ['건대입구역 2호선', '건대입구역 7호선', '어린이대공원역 7호선'],
 [],
 [],
 ['신설동역 1호선', '신설동역 2호선', '신설동역 우이신설선'],
 ['용두역 2호선'],
 ['제기동역 1호선'],
 ['청량리역 1호선', '청량리역 경의중앙선', '청량리역 경춘선', '청량리역 분당선'],
 [],
 ['장한평역 5호선'],
 [],
 [],
 ['회기역 1호선', '회기역 경의중앙선', '회기역 경춘선'],
 ['외대앞역 1호선', '신이문역 1호선'],
 [],
 ['사가정역 7호선', '면목역 7호선', '용마산역 7호선'],
 ['상봉역 7호선', '상봉역 경춘선', '상봉역 경의중앙선', '망우역 경춘선', '망우역 경의중앙선'],
 ['중화역 7호선', '중랑역 경의중앙선', '중랑역 경춘선'],
 ['먹골역 7호선'],
 ['양원역 경의중앙선', '신내역 경춘선'],
 ['봉화산(서울의료원)역 6호선'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['한성대입구역 4호선'],
 [],
 [],
 [],
 [],
 ['성신여대입구역 우이신설선'],
 [],
 [],
 ['성신여대입구역 4호선'],
 [],
 [],
 [],
 [],
 [],
 ['안암역 6호선'],
 [],
 [],
 [],
 [],
 ['보문역 6호선'],
 ['보문역 우이신설선'],
 [],
 ['북한산보국문역 우이신설선', '정릉역 우이신설선'],
 ['길음역 4호선'],
 ['고려대역 6호선'],
 ['월곡역 6호선'],
 ['상월곡역 6호선'],
 [],
 ['돌곶이역 6호선'],
 [],
 ['미아사거리역 4호선', '미아역 4호선', '삼양역 우이신설선', '삼양사거리역 우이신설선', '솔샘역 우이신설선'],
 [],
 ['수유(강북구청)역 4호선', '화계역 우이신설선', '가오리역 우이신설선'],
 ['북한산우이역 우이신설선', '4.19민주묘지역 우이신설선', '솔밭공원역 우이신설선'],
 [],
 [],
 ['방학역 1호선'],
 ['쌍문역 4호선', '창동역 4호선', '창동역 1호선', '녹천역 1호선'],
 ['도봉산역 1호선', '도봉역 1호선', '도봉산역 7호선'],
 [],
 ['광운대역 1호선', '석계역 1호선', '석계역 6호선', '월계역 1호선', '광운대역 경춘선'],
 ['태릉입구역 6호선', '공릉역 7호선', '태릉입구역 7호선', '화랑대역 6호선'],
 ['하계역 7호선'],
 ['노원역 4호선', '당고개역 4호선', '노원역 7호선', '수락산역 7호선', '상계역 4호선', '마들역 7호선'],
 ['중계역 7호선'],
 [],
 ['디지털미디어시티역 경의중앙선', '수색역 경의중앙선'],
 ['녹번역 3호선', '역촌역 6호선'],
 ['독바위역 6호선'],
 ['연신내역 3호선', '연신내역 6호선'],
 ['구산역 6호선'],
 ['불광역 3호선', '불광역 6호선'],
 [],
 ['응암역 6호선'],
 ['새절역 6호선', '신사역 3호선', '압구정역 3호선'],
 ['디지털미디어시티역 6호선', '증산역 6호선'],
 ['구파발역 3호선'],
 [],
 [],
 ['충정로역 2호선', '충정로역 5호선'],
 [],
 [],
 [],
 [],
 [],
 [],
 ['독립문역 3호선'],
 [],
 ['홍제역 3호선', '무악재역 3호선'],
 [],
 [],
 ['신촌역 경의중앙선'],
 [],
 [],
 [],
 [],
 [],
 ['가좌역 경의중앙선'],
 [],
 ['아현역 2호선', '애오개역 5호선'],
 ['공덕역 5호선', '공덕역 6호선'],
 [],
 ['공덕역 경의중앙선', '마포역 5호선', '공덕역 공항철도'],
 [],
 [],
 [],
 ['대흥역 6호선'],
 ['이대역 2호선'],
 ['신촌역 2호선', '서강대역 경의중앙선'],
 [],
 [],
 [],
 ['광흥창역 6호선'],
 ['상수역 6호선'],
 [],
 ['신정네거리역 2호선', '신정역 5호선', '양천구청역 2호선'],
 [],
 ['합정역 2호선'],
 ['홍대입구역 2호선', '홍대입구역 공항철도', '홍대입구역 경의중앙선'],
 ['합정역 6호선'],
 ['망원역 6호선'],
 [],
 ['월드컵경기장역 6호선', '마포구청역 6호선'],
 [],
 ['디지털미디어시티역 공항철도'],
 [],
 ['신정네거리역 2호선', '신정역 5호선', '양천구청역 2호선'],
 ['목동역 5호선', '신목동역 9호선'],
 [],
 [],
 ['염창역 9호선'],
 ['등촌역 9호선', '증미역 9호선'],
 ['화곡역 5호선', '까치산역 5호선', '까치산역 2호선', '우장산역 5호선'],
 ['가양역 9호선', '마곡역 5호선', '양천향교역 9호선'],
 ['발산역 5호선', '마곡나루역 9호선', '마곡나루역 공항철도'],
 [],
 [],
 ['송정역 5호선', '공항시장역 9호선'],
 ['김포공항역 공항철도',
  '김포공항역 9호선',
  '방화역 5호선',
  '신방화역 9호선',
  '개화산역 5호선',
  '김포공항역 5호선',
  '김포공항역 김포골드라인'],
 ['개화역 9호선'],
 [],
 [],
 [],
 [],
 ['신도림역 1호선', '신도림역 2호선', '도림천역 2호선'],
 ['구로역 1호선', '구로디지털단지역 2호선', '대림역 2호선', '구일역 1호선', '남구로역 7호선'],
 [],
 [],
 ['개봉역 1호선'],
 ['오류동역 1호선', '천왕역 7호선'],
 [],
 ['온수역 1호선', '온수역 7호선'],
 [],
 [],
 [],
 ['가산디지털단지역 1호선', '가산디지털단지역 7호선', '독산역 1호선'],
 [],
 ['금천구청역 1호선'],
 [],
 ['영등포역 1호선'],
 ['신길역 5호선'],
 [],
 [],
 [],
 ['영등포시장역 5호선'],
 [],
 [],
 [],
 ['여의나루역 5호선', '여의도역 5호선', '국회의사당역 9호선', '여의도역 9호선', '샛강역 9호선'],
 [],
 [],
 ['영등포구청역 2호선', '영등포구청역 5호선'],
 [],
 [],
 ['당산역 2호선', '당산역 9호선'],
 [],
 [],
 [],
 [],
 ['문래역 2호선'],
 [],
 [],
 [],
 [],
 ['양평역 5호선'],
 [],
 [],
 ['선유도역 9호선'],
 [],
 [],
 ['신길역 1호선', '대방역 1호선', '신풍역 7호선'],
 ['대림역 7호선'],
 [],
 [],
 ['노량진역 1호선', '노량진역 9호선'],
 ['숭실대입구역 7호선', '장승배기역 7호선'],
 ['상도역 7호선'],
 ['노들역 9호선'],
 ['흑석역 9호선'],
 ['동작역 4호선', '동작역 9호선'],
 ['사당역 2호선', '총신대입구(이수)역 4호선', '사당역 4호선', '이수역 7호선', '남성역 7호선'],
 ['보라매역 7호선', '신대방삼거리역 7호선'],
 [],
 [],
 ['서울대입구역 2호선', '낙성대역 2호선', '봉천역 2호선'],
 ['신림역 2호선', '신대방역 2호선'],
 [],
 [],
 ['방배역 2호선', '내방역 7호선', '남태령역 4호선'],
 ['양재시민의숲역 신분당선'],
 [],
 [],
 ['고속터미널역9호선', '잠원역 3호선', '반포역 7호선'],
 ['고속터미널역 3호선', '고속터미널역 7호선', '구반포역 9호선', '신반포역 9호선', '사평역 9호선'],
 ['양재역 3호선', '교대역 2호선', '남부터미널역 3호선', '서초역 2호선', '양재역 신분당선', '교대역 3호선'],
 [],
 [],
 ['청계산입구역 신분당선'],
 [],
 ['강남역 2호선', '신논현역 9호선', '강남역 신분당선', '역삼역 2호선'],
 ['개포동역 분당선', '구룡역 분당선'],
 ['청담역 7호선'],
 ['선릉역 2호선',
  '삼성역 2호선',
  '강남구청역 7호선',
  '봉은사역 9호선',
  '선정릉역 9호선',
  '선릉역 분당선',
  '강남구청역 분당선',
  '삼성중앙역 9호선',
  '선정릉역 분당선'],
 ['학여울역 3호선', '한티역 분당선', '대치역 3호선'],
 ['새절역 6호선', '신사역 3호선', '압구정역 3호선'],
 ['학동역 7호선', '논현역 7호선', '언주역 9호선'],
 ['압구정로데오역 분당선'],
 [],
 [],
 [],
 ['일원역 3호선', '대청역 3호선', '대모산입구역 분당선'],
 ['수서역 3호선', '수서역 분당선'],
 ['매봉역 3호선', '도곡역 3호선', '도곡역 분당선'],
 [],
 ['잠실역 2호선', '종합운동장역 2호선', '잠실새내역 2호선', '종합운동장역 9호선', '삼전역 9호선', '서울메트로9호선운영'],
 ['잠실역 8호선', '잠실나루역 2호선', '몽촌토성역 8호선'],
 [],
 ['송파나루역 9호선'],
 ['석촌역 8호선', '석촌역 9호선'],
 ['석촌고분역 9호선'],
 ['가락시장역 3호선', '가락시장역 8호선', '송파역 8호선', '경찰병원역 3호선'],
 ['문정역 8호선'],
 ['복정역 8호선', '장지역 8호선', '복정역 분당선'],
 ['올림픽공원역 5호선', '방이역 5호선', '올림픽공원역 9호선', '한성백제역 9호선'],
 ['오금역 3호선', '개롱역 5호선', '오금역 5호선'],
 ['거여역 5호선'],
 ['마천역 5호선'],
 [],
 ['명일역 5호선', '굽은다리역 5호선'],
 ['고덕역 5호선'],
 ['상일동역 5호선'],
 ['길동역 5호선'],
 ['둔촌동역 5호선', '중앙보훈병원역 9호선', '둔촌오륜역 9호선'],
 ['암사역 8호선'],
 ['강동구청역 8호선'],
 ['천호역 5호선', '강동역 5호선', '천호역 8호선'],
 []]

In [60]:
origin_data['station'] = arr
origin_data

,Unnamed: 0,id,address,gu,dong,mac_score,lot_score,burgerking_score,seveneleven_score,cu_score,...,first_mapy,second_mapx,second_mapy,third_mapx,third_mapy,elementary_count,middle_count,high_count,park_count,station
0,0,0,서울특별시,0,0,0.00,0.00,0.0,0.00,0.00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0,0,[]
1,1,1,서울특별시 종로구,0,0,0.00,0.00,0.0,0.00,0.00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0,0,[]
2,2,2,서울특별시 종로구 청운동,종로구,청운동,0.00,0.00,0.0,0.00,0.00,...,127.085704,37.592065,127.018260,37.536423,126.969346,1,1,3,1,[]
3,3,3,서울특별시 종로구 신교동,종로구,신교동,0.00,0.00,0.0,0.00,0.13,...,126.965840,37.536700,126.992151,37.527015,126.905253,0,0,0,0,[]
4,4,4,서울특별시 종로구 궁정동,종로구,궁정동,0.00,0.00,0.0,0.00,0.00,...,126.982123,37.573102,126.997921,37.572859,127.003417,0,0,0,1,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
488,488,488,서울특별시 강동구 둔촌동,강동구,둔촌동,3.33,0.00,0.0,0.85,0.67,...,127.103926,37.509454,126.880425,37.652731,127.028710,4,3,2,5,"[둔촌동역 5호선, 중앙보훈병원역 9호선, 둔촌오륜역 9호선]"
489,489,489,서울특별시 강동구 암사동,강동구,암사동,0.00,1.25,0.0,1.06,1.73,...,126.938775,37.492678,126.917721,37.494129,126.840746,3,2,1,13,[암사역 8호선]
490,490,490,서울특별시 강동구 성내동,강동구,성내동,3.33,1.25,10.0,2.55,2.67,...,126.911558,37.474116,126.976721,37.533889,127.003955,2,1,0,9,[강동구청역 8호선]
491,491,491,서울특별시 강동구 천호동,강동구,천호동,3.33,1.25,0.0,4.68,2.93,...,126.990860,37.562462,127.029586,37.584277,127.017551,3,2,1,17,"[천호역 5호선, 강동역 5호선, 천호역 8호선]"
492,492,492,서울특별시 강동구 강일동,강동구,강일동,0.00,1.25,0.0,0.64,0.53,...,126.909195,37.598415,127.020288,37.561666,126.956170,3,2,1,4,[]

In [66]:
for idx in range(len(origin_data)):
    if origin_data['station'][idx]:
        origin_data['station'][idx] = str(origin_data['station'][idx])
        origin_data['station'][idx] = origin_data['station'][idx][1:-1]
    else:
        origin_data['station'][idx] = '없음'

c:\program files\python35\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
c:\program files\python35\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [67]:
origin_data

,Unnamed: 0,id,address,gu,dong,mac_score,lot_score,burgerking_score,seveneleven_score,cu_score,...,first_mapy,second_mapx,second_mapy,third_mapx,third_mapy,elementary_count,middle_count,high_count,park_count,station
0,0,0,서울특별시,0,0,0.00,0.00,0.0,0.00,0.00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0,0,
1,1,1,서울특별시 종로구,0,0,0.00,0.00,0.0,0.00,0.00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0,0,
2,2,2,서울특별시 종로구 청운동,종로구,청운동,0.00,0.00,0.0,0.00,0.00,...,127.085704,37.592065,127.018260,37.536423,126.969346,1,1,3,1,
3,3,3,서울특별시 종로구 신교동,종로구,신교동,0.00,0.00,0.0,0.00,0.13,...,126.965840,37.536700,126.992151,37.527015,126.905253,0,0,0,0,
4,4,4,서울특별시 종로구 궁정동,종로구,궁정동,0.00,0.00,0.0,0.00,0.00,...,126.982123,37.573102,126.997921,37.572859,127.003417,0,0,0,1,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
488,488,488,서울특별시 강동구 둔촌동,강동구,둔촌동,3.33,0.00,0.0,0.85,0.67,...,127.103926,37.509454,126.880425,37.652731,127.028710,4,3,2,5,"촌동역 5호선', '중앙보훈병원역 9호선', '둔촌오륜역 9호"
489,489,489,서울특별시 강동구 암사동,강동구,암사동,0.00,1.25,0.0,1.06,1.73,...,126.938775,37.492678,126.917721,37.494129,126.840746,3,2,1,13,사역 8호
490,490,490,서울특별시 강동구 성내동,강동구,성내동,3.33,1.25,10.0,2.55,2.67,...,126.911558,37.474116,126.976721,37.533889,127.003955,2,1,0,9,동구청역 8호
491,491,491,서울특별시 강동구 천호동,강동구,천호동,3.33,1.25,0.0,4.68,2.93,...,126.990860,37.562462,127.029586,37.584277,127.017551,3,2,1,17,"호역 5호선', '강동역 5호선', '천호역 8호"
492,492,492,서울특별시 강동구 강일동,강동구,강일동,0.00,1.25,0.0,0.64,0.53,...,126.909195,37.598415,127.020288,37.561666,126.956170,3,2,1,4,

In [65]:
origin_data.to_csv("지하철_교육시설포함_최종.txt", mode="w")